version: "3"

services:
  hello:
    build: .
    image: hello:latest
    ports:
      - "8000:8000"
  authserver:
    build: .
    image: authserver:latest
    command: ["/bin/authserver"]
    ports:
      - "8001:8001"
  envoy:
    image: envoyproxy/envoy:v1.27-latest
    ports:
      - "10000:10000"
    volumes:
      - ./etc/envoy/envoy.yaml:/etc/envoy/envoy.yaml
